# Generated by Django 4.2.16 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scenario", models.CharField(default="Unknown", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("gorilla_strength", models.FloatField(blank=True, null=True)),
                ("human_intelligence", models.IntegerField(blank=True, null=True)),
                ("number_of_humans", models.IntegerField(blank=True, null=True)),
                (
                    "human_team_strategy",
                    models.CharField(default="Unknown", max_length=100),
                ),
                (
                    "estimated_outcome",
                    models.CharField(default="Unknown", max_length=100),
                ),
            ],
        ),
    ]
