# Generated by Django 4.2.16 on 2025-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("score", models.IntegerField()),
                ("date_played", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
